### Specify CircleCI version
version: 2.1

### Specify Programming Context
orbs:
    ## NodeJs
    # Syntax:
    # circleci/node@<x.y.z>
    node: circleci/node@13.12.0

### Define the jobs/tasks
jobs:
    ## Task name
    # Syntax:
    # <task-name>+
    install:
        ## Env variable
        # Syntax:
        # environment
        #   [<ENV-NAME>: <VALUE>]+

        ## Specify commands to run
        # Syntax:
        # steps: <shell-command>
        # or
        # steps:
        #   - run: ..
        steps:
            ## Run single/multiple commands
            # Syntax:
            # [- run: <shell-command>]+
            # or
            # [- run:
            #   name: <description>
            #   command: <shell-command>]+
            - run: npm i -g gulp-cli

    test:
        steps:
            - run: npm run test-with-cov && npm run test-collect-cov

### Execute the jobs/task
workflows:
    ## Specify name of execution
    # Syntax:
    # <execution-name>+
    main:
        jobs:
            # Specify task to run defined above in order
            # Syntax:
            # - <task-name>+
            - install
            - test
